catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set vpp_optimize_level 0
open_project TransposeConv2d_kernel
set_top TransposeConv2d_kernel
add_files "/ihome/ageorge/cjg91/dev/transposed-conv-accel/hw/src/kernel.cpp" -cflags " -g -I /ihome/ageorge/cjg91/dev/transposed-conv-accel/hw/src "
open_solution solution
set_part xcu200-fsgd2104-2-e
create_clock -period 300.000000MHz -name default
config_sdx -target xocc
config_rtl -kernel_profile
config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
config_debug -enable
set_clock_uncertainty 27.000000%
config_rtl -enable_maxiConservative=1
config_interface -m_axi_addr64
config_compile -skip_transform
config_export -format ip_catalog -ipname TransposeConv2d_kernel
csynth_design
close_project
puts "HLS completed successfully"
exit
